### ISSUE TITLE
vulnerable against reflection, replay, reordering, and nonce-reuse

### ISSUE THREAD

**Issue by t0b0** [nknorg/encrypted-stream#7]
Each packet in the stream is encrypted with its own, randomly generated nonce. This can lead to nonce re-use (when using AES GCM) if encrypting more than 2^32 packets. That would mean that keys need to be rotated that often. I doubt a user of the library would do that. 
Also, because there is no sense of direction, an attacker could reflect a packet sent by a client back to the client and the client would mistake it as a response from the server. 
There is also no authenticated packet counter, meaning that a man in the middle (MITM) attacker could replay and re-order packets without detection by the recipient. 

Overall, I think it'd be fair to say that this library achieves confidentiality in presence of an eavesdropper, but no security in presence of a MITM.

**Comment by yilunzhang** [comment]
@t0b0 These issues should be fixed by #8. In the future we can add native support for noise framework for easier usage.

**Comment by yilunzhang** [comment]
Closed for inactivity. Feel free to reopen it if needed
